#!/usr/bin/env python3
"""Download songs from a Spotify playlist CSV using yt-dlp.

The CSV is expected to contain Spotify export columns:
Track Name, Album Name, and Artist Name(s).
"""

from __future__ import annotations

import argparse
import base64
import csv
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import unicodedata
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode, urlparse
from urllib.request import Request, urlopen


INVALID_PATH_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
SPACE_RUN = re.compile(r"\s+")
WORD_CHARS = re.compile(r"[^a-z0-9]+")
BAD_MATCH_WORDS = {
    "8d",
    "bass",
    "boosted",
    "clean",
    "cover",
    "edit",
    "instrumental",
    "karaoke",
    "live",
    "lyrics",
    "nightcore",
    "reaction",
    "remaster",
    "remastered",
    "remix",
    "slowed",
    "sped",
}
GOOD_MATCH_PHRASES = (
    "official audio",
    "provided to youtube",
    "auto-generated by youtube",
    "topic",
)
PUNCTUATION_TRANSLATION = str.maketrans(
    {
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "…": "",
    }
)


@dataclass
class TrackResult:
    status: str
    artists: str
    track: str
    destination: Path | None = None
    error: str | None = None
    playlist_title: str | None = None

    @property
    def label(self) -> str:
        return f"{self.artists} - {self.track}"


@dataclass
class TrackMetadata:
    track: str
    artists: str
    album: str
    destination: Path
    source_url: str | None = None
    year: str | None = None
    track_number: int | None = None
    artwork_url: str | None = None
    playlist_title: str | None = None
    duration_ms: int | None = None


@dataclass
class ListenBrainzPlaylist:
    mbid: str
    title: str
    plex_title: str
    source_patch: str | None = None
    date: str | None = None


def clean_path_part(value: str, fallback: str) -> str:
    value = value.strip().replace("\ufeff", "")
    value = INVALID_PATH_CHARS.sub("-", value)
    value = SPACE_RUN.sub(" ", value)
    value = value.strip(" .-_")
    return value or fallback


def clean_track_filename(track: str, artists: str) -> str:
    """Create a tidy file stem, stripping common artist prefixes/suffixes."""
    name = clean_path_part(track, "Unknown Track")

    artist_names = [
        part.strip()
        for part in re.split(r",|;|&|\bfeat\.?\b|\bft\.?\b", artists, flags=re.I)
        if part.strip()
    ]

    for artist in artist_names:
        artist_pattern = re.escape(clean_path_part(artist, artist))
        name = re.sub(rf"^\s*{artist_pattern}\s*[-_–—:]+\s*", "", name, flags=re.I)
        name = re.sub(rf"\s*[-_–—:]+\s*{artist_pattern}\s*$", "", name, flags=re.I)

    return clean_path_part(name, "Unknown Track")


def primary_artist_name(artists: str) -> str:
    """Use the main artist for folder organization, ignoring featured artists."""
    primary = re.split(
        r";|,|&|\bfeat\.?\b|\bfeaturing\b|\bft\.?\b|\bwith\b",
        artists,
        maxsplit=1,
        flags=re.I,
    )[0]
    return clean_path_part(primary, "Unknown Artist")


def build_track_metadata(
    track: str,
    artists: str,
    album: str,
    output_dir: Path,
    source_url: str | None = None,
    year: str | None = None,
    track_number: int | None = None,
    artwork_url: str | None = None,
    playlist_title: str | None = None,
    duration_ms: int | None = None,
) -> TrackMetadata:
    """Build the final artist/album/track path from Spotify metadata."""
    track = track.strip()
    artists = artists.strip()
    album = album.strip()

    artist_dir = primary_artist_name(artists)
    album_dir = clean_path_part(album, "Unknown Album")
    track_stem = clean_track_filename(track, artists)
    destination = output_dir / artist_dir / album_dir / f"{track_stem}.mp3"

    return TrackMetadata(
        track=track,
        artists=artists,
        album=album,
        destination=destination,
        source_url=source_url,
        year=year,
        track_number=track_number,
        artwork_url=artwork_url,
        playlist_title=playlist_title,
        duration_ms=duration_ms,
    )


def track_from_csv_row(row: dict[str, str], output_dir: Path) -> TrackMetadata:
    """Build metadata from Spotify CSV columns."""
    track_number = row.get("Track Number") or row.get("Track #") or row.get("Disc Number")
    return build_track_metadata(
        row["Track Name"],
        row["Artist Name(s)"],
        row.get("Album Name", ""),
        output_dir,
        year=release_year(row.get("Release Date") or row.get("Year")),
        track_number=numeric_value(track_number),
        artwork_url=(
            row.get("Album Image URL")
            or row.get("Artwork URL")
            or row.get("Image URL")
            or row.get("Cover URL")
        ),
    )


def read_tracks(csv_path: Path, output_dir: Path) -> list[TrackMetadata]:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        required = {"Track Name", "Album Name", "Artist Name(s)"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise RuntimeError(
                f"{csv_path} is missing required CSV column(s): {', '.join(sorted(missing))}"
            )

        return [
            track_from_csv_row(row, output_dir)
            for row in reader
            if row.get("Track Name") and row.get("Artist Name(s)")
        ]


def parse_spotify_source(source: str) -> tuple[str, str] | None:
    if source.startswith("spotify:"):
        parts = source.split(":")
        if len(parts) >= 3 and parts[1] in {"track", "album", "playlist"}:
            return parts[1], parts[2]
        return None

    parsed = urlparse(source)
    if parsed.netloc not in {"open.spotify.com", "play.spotify.com"}:
        return None

    path_parts = [part for part in parsed.path.split("/") if part]
    if path_parts and re.fullmatch(r"intl-[a-z]{2}", path_parts[0], flags=re.I):
        path_parts = path_parts[1:]

    if len(path_parts) >= 2 and path_parts[0] in {"track", "album", "playlist"}:
        return path_parts[0], path_parts[1]

    return None


def parse_youtube_music_source(source: str) -> bool:
    parsed = urlparse(source)
    if parsed.netloc not in {
        "music.youtube.com",
        "www.music.youtube.com",
        "youtube.com",
        "www.youtube.com",
    }:
        return False

    if parsed.path == "/playlist" and "list=" in parsed.query:
        return True

    return parsed.path == "/watch" and "v=" in parsed.query


def listenbrainz_playlist_mbid_from_identifier(identifier: object) -> str | None:
    if not isinstance(identifier, str):
        return None

    parsed = urlparse(identifier)
    path_parts = [part for part in parsed.path.split("/") if part]
    if path_parts and path_parts[0] == "playlist" and len(path_parts) >= 2:
        return path_parts[1]

    if re.fullmatch(r"[0-9a-fA-F-]{36}", identifier):
        return identifier

    return None


def parse_listenbrainz_source(source: str) -> tuple[str, str] | None:
    parsed = urlparse(source)
    if parsed.netloc in {"listenbrainz.org", "www.listenbrainz.org"}:
        path_parts = [part for part in parsed.path.split("/") if part]
        if len(path_parts) >= 2 and path_parts[0] == "playlist":
            return "playlist", path_parts[1]
        if len(path_parts) >= 2 and path_parts[0] == "user":
            return "createdfor", path_parts[1]
        return None

    if not source.startswith("listenbrainz:"):
        return None

    parts = source.split(":")
    if len(parts) == 2 and parts[1]:
        return "createdfor", parts[1]
    if len(parts) >= 3 and parts[1] in {"createdfor", "user", "playlist"} and parts[2]:
        return parts[1], parts[2]

    return None


def spotify_request(url: str, token: str) -> dict:
    request = Request(url, headers={"Authorization": f"Bearer {token}"})
    try:
        with urlopen(request) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        details = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Spotify API error {exc.code}: {details}") from exc
    except URLError as exc:
        raise RuntimeError(f"Spotify API request failed: {exc.reason}") from exc


def json_request(url: str, headers: dict[str, str] | None = None) -> dict:
    request = Request(url, headers=headers or {})
    try:
        with urlopen(request) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        details = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP error {exc.code} for {url}: {details}") from exc
    except URLError as exc:
        raise RuntimeError(f"Request failed for {url}: {exc.reason}") from exc


def get_spotify_token(client_id: str, client_secret: str) -> str:
    credentials = base64.b64encode(f"{client_id}:{client_secret}".encode("utf-8")).decode("ascii")
    body = b"grant_type=client_credentials"
    request = Request(
        "https://accounts.spotify.com/api/token",
        data=body,
        headers={
            "Authorization": f"Basic {credentials}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
    )

    try:
        with urlopen(request) as response:
            data = json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        details = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Spotify auth failed {exc.code}: {details}") from exc
    except URLError as exc:
        raise RuntimeError(f"Spotify auth failed: {exc.reason}") from exc

    return data["access_token"]


def load_spotify_credentials(args: argparse.Namespace) -> tuple[str | None, str | None]:
    client_id = args.spotify_client_id or os.environ.get("SPOTIFY_CLIENT_ID")
    client_secret = args.spotify_client_secret or os.environ.get("SPOTIFY_CLIENT_SECRET")
    return client_id, client_secret


def artist_names(artists: list[dict]) -> str:
    return ";".join(artist["name"] for artist in artists if artist.get("name"))


def release_year(release_date: str | None) -> str | None:
    if not release_date:
        return None
    match = re.match(r"\d{4}", release_date)
    return match.group(0) if match else None


def numeric_value(value: object) -> int | None:
    if isinstance(value, int):
        return value
    if isinstance(value, str) and value.isdigit():
        return int(value)
    return None


def largest_image_url(images: list[dict] | None) -> str | None:
    if not images:
        return None

    def image_area(image: dict) -> int:
        return int(image.get("width") or 0) * int(image.get("height") or 0)

    image = max(images, key=image_area)
    return image.get("url")


def musicbrainz_artwork_url(metadata: dict) -> str | None:
    release_mbid = metadata.get("caa_release_mbid")
    caa_id = metadata.get("caa_id")
    if release_mbid and caa_id:
        return f"https://coverartarchive.org/release/{release_mbid}/{caa_id}.jpg"
    return None


def listenbrainz_artist_credit(track: dict) -> str:
    extension = track.get("extension") or {}
    jspf = extension.get("https://musicbrainz.org/doc/jspf#track") or {}
    metadata = jspf.get("additional_metadata") or {}
    artists = metadata.get("artists")
    if isinstance(artists, list) and artists:
        credit = "".join(
            f"{artist.get('artist_credit_name', '')}{artist.get('join_phrase', '')}"
            for artist in artists
            if isinstance(artist, dict)
        ).strip()
        if credit:
            return credit

    return str(track.get("creator") or "").strip()


def listenbrainz_playlist_extension(playlist: dict) -> dict:
    extension = playlist.get("extension") or {}
    return extension.get("https://musicbrainz.org/doc/jspf#playlist") or {}


def listenbrainz_playlist_source_patch(playlist: dict) -> str | None:
    jspf = listenbrainz_playlist_extension(playlist)
    metadata = jspf.get("additional_metadata") or {}
    algorithm_metadata = metadata.get("algorithm_metadata") or {}
    source_patch = algorithm_metadata.get("source_patch")
    return str(source_patch) if source_patch else None


def listenbrainz_playlist_date(playlist: dict) -> str | None:
    date_value = playlist.get("date")
    if isinstance(date_value, str):
        match = re.match(r"\d{4}-\d{2}-\d{2}", date_value)
        if match:
            return match.group(0)

    title = str(playlist.get("title") or "")
    match = re.search(r"\b(\d{4}-\d{2}-\d{2})\b", title)
    return match.group(1) if match else None


def listenbrainz_plex_playlist_title(playlist: dict) -> str:
    source_patch = listenbrainz_playlist_source_patch(playlist)
    playlist_date = listenbrainz_playlist_date(playlist)
    if source_patch == "weekly-exploration" and playlist_date:
        return f"Weekly Playlist {playlist_date}"
    return str(playlist.get("title") or "ListenBrainz Playlist")


def metadata_from_listenbrainz_track(
    track: dict,
    output_dir: Path,
    playlist_title: str,
) -> TrackMetadata | None:
    title = str(track.get("title") or "").strip()
    artists = listenbrainz_artist_credit(track)
    if not title or not artists:
        return None

    extension = track.get("extension") or {}
    jspf = extension.get("https://musicbrainz.org/doc/jspf#track") or {}
    metadata = jspf.get("additional_metadata") or {}

    return build_track_metadata(
        title,
        artists,
        str(track.get("album") or playlist_title),
        output_dir,
        artwork_url=musicbrainz_artwork_url(metadata),
        playlist_title=playlist_title,
        duration_ms=numeric_value(track.get("duration")),
    )


def read_listenbrainz_playlist(
    playlist_mbid: str,
    output_dir: Path,
    playlist_title_override: str | None = None,
) -> list[TrackMetadata]:
    api_base = "https://api.listenbrainz.org/1"
    data = json_request(f"{api_base}/playlist/{quote(playlist_mbid)}")
    playlist = data.get("playlist") or {}
    title = str(playlist.get("title") or f"ListenBrainz {playlist_mbid}")
    plex_title = playlist_title_override or listenbrainz_plex_playlist_title(playlist)
    tracks = []
    for track in playlist.get("track") or []:
        metadata = metadata_from_listenbrainz_track(track, output_dir, plex_title)
        if metadata:
            tracks.append(metadata)

    print(f"[source] Resolved {len(tracks)} track(s) from ListenBrainz playlist: {title} -> {plex_title}")
    return tracks


def list_listenbrainz_playlists(username: str, mode: str) -> list[ListenBrainzPlaylist]:
    api_base = "https://api.listenbrainz.org/1"
    endpoint = "playlists" if mode == "user" else "playlists/createdfor"
    playlists: list[ListenBrainzPlaylist] = []
    offset = 0
    count = 100

    while True:
        data = json_request(
            f"{api_base}/user/{quote(username)}/{endpoint}?{urlencode({'count': count, 'offset': offset})}"
        )
        page_items = data.get("playlists") or []
        for item in page_items:
            playlist = item.get("playlist") or {}
            mbid = listenbrainz_playlist_mbid_from_identifier(playlist.get("identifier"))
            title = playlist.get("title")
            if mbid and title:
                playlists.append(
                    ListenBrainzPlaylist(
                        mbid=mbid,
                        title=str(title),
                        plex_title=listenbrainz_plex_playlist_title(playlist),
                        source_patch=listenbrainz_playlist_source_patch(playlist),
                        date=listenbrainz_playlist_date(playlist),
                    )
                )

        if len(page_items) < count:
            break
        offset += count

    return playlists


def read_listenbrainz_source(source: str, output_dir: Path) -> list[TrackMetadata]:
    parsed = parse_listenbrainz_source(source)
    if not parsed:
        raise RuntimeError(f"Not a supported ListenBrainz source: {source}")

    mode, value = parsed
    if mode == "playlist":
        print(f"[source] Reading ListenBrainz playlist: {value}")
        return read_listenbrainz_playlist(value, output_dir)

    print(f"[source] Reading ListenBrainz {mode} playlists for: {value}")
    playlists = list_listenbrainz_playlists(value, mode)
    if mode == "createdfor":
        playlists = [playlist for playlist in playlists if playlist.source_patch == "weekly-exploration"]
    if not playlists:
        print(f"[source] No ListenBrainz {mode} playlists found for {value}")
        return []

    tracks: list[TrackMetadata] = []
    for playlist in playlists:
        tracks.extend(read_listenbrainz_playlist(playlist.mbid, output_dir, playlist.plex_title))

    return tracks


def metadata_from_spotify_track(track: dict, output_dir: Path) -> TrackMetadata | None:
    if not track or track.get("type") != "track" or track.get("is_local"):
        return None

    album = track.get("album") or {}
    return build_track_metadata(
        track.get("name", ""),
        artist_names(track.get("artists") or []),
        album.get("name", ""),
        output_dir,
        year=release_year(album.get("release_date")),
        track_number=numeric_value(track.get("track_number")),
        artwork_url=largest_image_url(album.get("images")),
    )


def clean_youtube_music_album_title(title: str) -> str:
    title = title.strip()
    for prefix in ("Album - ", "Playlist - "):
        if title.startswith(prefix):
            return title.removeprefix(prefix).strip()
    return title


def clean_youtube_music_artist(value: str) -> str:
    value = value.strip()
    return re.sub(r"\s+-\s+Topic$", "", value).strip()


def youtube_music_entry_url(entry: dict) -> str | None:
    if entry.get("webpage_url"):
        return entry["webpage_url"]
    if entry.get("original_url"):
        return entry["original_url"]
    if entry.get("url") and str(entry["url"]).startswith(("http://", "https://")):
        return entry["url"]
    if entry.get("id"):
        return f"https://music.youtube.com/watch?v={entry['id']}"
    return None


def youtube_music_thumbnail_url(entry: dict) -> str | None:
    thumbnails = entry.get("thumbnails")
    if isinstance(thumbnails, list):
        return largest_image_url([item for item in thumbnails if isinstance(item, dict)])

    thumbnail = entry.get("thumbnail")
    if isinstance(thumbnail, str):
        return thumbnail

    return None


def metadata_from_youtube_music_entry(
    entry: dict,
    output_dir: Path,
    fallback_album: str,
) -> TrackMetadata | None:
    title = entry.get("track") or entry.get("alt_title") or entry.get("title") or ""
    title = title.strip()
    if not title or title.startswith("["):
        return None

    artists = entry.get("artists")
    if isinstance(artists, list):
        artist = ";".join(str(item) for item in artists if item)
    else:
        artist = entry.get("artist") or entry.get("creator") or entry.get("uploader") or entry.get("channel") or ""
    artist = clean_youtube_music_artist(artist)

    album = entry.get("album") or fallback_album or entry.get("playlist_title") or "YouTube Music"
    source_url = youtube_music_entry_url(entry)
    return build_track_metadata(
        title,
        artist,
        album,
        output_dir,
        source_url=source_url,
        year=release_year(
            str(entry.get("release_year") or entry.get("release_date") or entry.get("upload_date") or "")
        ),
        track_number=numeric_value(entry.get("track_number")),
        artwork_url=youtube_music_thumbnail_url(entry),
    )


def read_youtube_music_url(
    source: str,
    output_dir: Path,
    cookie_args: list[str],
    metadata_limit: int | None,
) -> list[TrackMetadata]:
    print(f"[source] Reading YouTube Music metadata: {source}")
    cmd = [
        "yt-dlp",
        "--dump-single-json",
        "--ignore-errors",
        "--no-warnings",
        *cookie_args,
    ]
    if metadata_limit is not None:
        cmd.extend(["--playlist-end", str(metadata_limit)])
    cmd.append(source)

    completed = subprocess.run(cmd, check=False, capture_output=True, text=True)
    if not completed.stdout.strip():
        message = completed.stderr.strip() or f"yt-dlp exited with status {completed.returncode}"
        raise RuntimeError(f"Could not read YouTube Music metadata for {source}: {message}")

    try:
        data = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        message = completed.stderr.strip() or f"yt-dlp exited with status {completed.returncode}"
        raise RuntimeError(f"Could not parse YouTube Music metadata for {source}: {message}") from exc
    fallback_album = clean_youtube_music_album_title(data.get("title") or "YouTube Music")
    entries = data.get("entries")
    if not entries:
        metadata = metadata_from_youtube_music_entry(data, output_dir, fallback_album)
        if metadata:
            print(f"[source] Resolved 1 track from YouTube Music: {metadata.artists} - {metadata.track}")
        return [metadata] if metadata else []

    tracks = []
    for entry in entries:
        if not entry:
            continue
        metadata = metadata_from_youtube_music_entry(entry, output_dir, fallback_album)
        if metadata:
            tracks.append(metadata)

    if not tracks and completed.returncode != 0:
        message = completed.stderr.strip() or f"yt-dlp exited with status {completed.returncode}"
        if "Private video" in message or "Sign in" in message:
            message = (
                "No readable YouTube Music tracks were found. The playlist may contain private videos; "
                "try --cookies-from-browser chrome or --cookies /path/to/cookies.txt."
            )
        raise RuntimeError(f"Could not read YouTube Music metadata for {source}: {message}")

    print(f"[source] Resolved {len(tracks)} track(s) from YouTube Music")
    return tracks


def read_spotify_url(source: str, output_dir: Path, token: str) -> list[TrackMetadata]:
    parsed = parse_spotify_source(source)
    if not parsed:
        raise RuntimeError(f"Not a supported Spotify share URL or URI: {source}")

    source_type, source_id = parsed
    api_base = "https://api.spotify.com/v1"

    if source_type == "track":
        track = spotify_request(f"{api_base}/tracks/{source_id}", token)
        metadata = metadata_from_spotify_track(track, output_dir)
        return [metadata] if metadata else []

    if source_type == "album":
        album = spotify_request(f"{api_base}/albums/{source_id}", token)
        album_name = album.get("name", "")
        album_year = release_year(album.get("release_date"))
        album_artwork_url = largest_image_url(album.get("images"))
        tracks: list[TrackMetadata] = []
        next_url = f"{api_base}/albums/{source_id}/tracks?limit=50"
        while next_url:
            page = spotify_request(next_url, token)
            for track in page.get("items", []):
                tracks.append(
                    build_track_metadata(
                        track.get("name", ""),
                        artist_names(track.get("artists") or []),
                        album_name,
                        output_dir,
                        year=album_year,
                        track_number=numeric_value(track.get("track_number")),
                        artwork_url=album_artwork_url,
                    )
                )
            next_url = page.get("next")
        return tracks

    tracks = []
    next_url = f"{api_base}/playlists/{source_id}/tracks?limit=100"
    while next_url:
        page = spotify_request(next_url, token)
        for item in page.get("items", []):
            metadata = metadata_from_spotify_track(item.get("track") or {}, output_dir)
            if metadata:
                tracks.append(metadata)
        next_url = page.get("next")
    return tracks


def get_spotify_token_for_sources(sources: list[str], args: argparse.Namespace) -> str | None:
    if not any(parse_spotify_source(source) for source in sources):
        return None

    client_id, client_secret = load_spotify_credentials(args)
    if not client_id or not client_secret:
        raise RuntimeError(
            "Spotify URL mode needs credentials. Set SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET, "
            "or pass --spotify-client-id and --spotify-client-secret."
        )

    return get_spotify_token(client_id, client_secret)


def read_source(
    source: str,
    output_dir: Path,
    args: argparse.Namespace,
    spotify_token: str | None,
    cookie_args: list[str],
) -> list[TrackMetadata]:
    if parse_listenbrainz_source(source):
        return read_listenbrainz_source(source, output_dir)

    if parse_spotify_source(source):
        print(f"[source] Reading Spotify metadata: {source}")
        if not spotify_token:
            raise RuntimeError(f"Spotify token was not loaded for source: {source}")
        return read_spotify_url(source, output_dir, spotify_token)

    if parse_youtube_music_source(source):
        return read_youtube_music_url(source, output_dir, cookie_args, args.limit)

    csv_path = Path(source).expanduser().resolve()
    if not csv_path.exists():
        raise RuntimeError(f"CSV not found: {csv_path}")

    print(f"[source] Reading CSV: {csv_path}")
    return read_tracks(csv_path, output_dir)


def read_sources(
    sources: list[str],
    output_dir: Path,
    args: argparse.Namespace,
    cookie_args: list[str],
) -> list[TrackMetadata]:
    tracks: list[TrackMetadata] = []
    spotify_token = get_spotify_token_for_sources(sources, args)

    for source in sources:
        source_tracks = read_source(source, output_dir, args, spotify_token, cookie_args)
        print(f"[source] {source}: {len(source_tracks)} track(s)")
        tracks.extend(source_tracks)

    return tracks


def build_cookie_args(args: argparse.Namespace) -> list[str]:
    cookie_args: list[str] = []

    if args.cookies_from_browser:
        cookie_args.extend(["--cookies-from-browser", args.cookies_from_browser])

    if args.cookies:
        cookie_args.extend(["--cookies", str(args.cookies.expanduser().resolve())])

    return cookie_args


def load_env_file(path: Path) -> None:
    if not path.exists():
        return

    with path.open("r", encoding="utf-8") as env_file:
        for line in env_file:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


def synchsafe_size(size: int) -> bytes:
    return bytes(
        [
            (size >> 21) & 0x7F,
            (size >> 14) & 0x7F,
            (size >> 7) & 0x7F,
            size & 0x7F,
        ]
    )


def read_synchsafe_size(data: bytes) -> int:
    return (data[0] << 21) | (data[1] << 14) | (data[2] << 7) | data[3]


def id3_text_frame(frame_id: str, value: str | int | None) -> bytes:
    if value is None or str(value).strip() == "":
        return b""

    payload = b"\x01" + str(value).encode("utf-16")
    return frame_id.encode("ascii") + len(payload).to_bytes(4, "big") + b"\x00\x00" + payload


def id3_url_frame(frame_id: str, value: str | None) -> bytes:
    if not value or not value.startswith(("http://", "https://")):
        return b""

    payload = value.encode("ascii", errors="ignore")
    return frame_id.encode("ascii") + len(payload).to_bytes(4, "big") + b"\x00\x00" + payload


def guess_image_mime_type(url: str, content_type: str | None) -> str:
    content_type = (content_type or "").split(";", 1)[0].strip().lower()
    if content_type in {"image/jpeg", "image/png"}:
        return content_type

    path = urlparse(url).path.lower()
    if path.endswith(".png"):
        return "image/png"
    return "image/jpeg"


def fetch_artwork(artwork_url: str | None) -> tuple[str, bytes] | None:
    if not artwork_url:
        return None

    request = Request(artwork_url, headers={"User-Agent": "MDL/1.0"})
    try:
        with urlopen(request, timeout=20) as response:
            content_type = response.headers.get("Content-Type")
            image = response.read(10 * 1024 * 1024 + 1)
    except (HTTPError, URLError, TimeoutError, OSError) as exc:
        print(f"[metadata] artwork skipped: {exc}")
        return None

    if len(image) > 10 * 1024 * 1024:
        print("[metadata] artwork skipped: image is larger than 10 MB")
        return None

    return guess_image_mime_type(artwork_url, content_type), image


def id3_apic_frame(artwork: tuple[str, bytes] | None) -> bytes:
    if not artwork:
        return b""

    mime_type, image = artwork
    payload = b"\x00" + mime_type.encode("ascii") + b"\x00\x03\x00" + image
    return b"APIC" + len(payload).to_bytes(4, "big") + b"\x00\x00" + payload


def strip_existing_id3v2(data: bytes) -> bytes:
    if len(data) < 10 or data[:3] != b"ID3":
        return data

    flags = data[5]
    tag_size = 10 + read_synchsafe_size(data[6:10])
    if flags & 0x10:
        tag_size += 10
    return data[tag_size:]


def write_mp3_metadata(path: Path, track: TrackMetadata) -> None:
    frames = b"".join(
        [
            id3_text_frame("TIT2", track.track),
            id3_text_frame("TPE1", track.artists.replace(";", "/")),
            id3_text_frame("TPE2", track.artists.split(";", 1)[0].strip()),
            id3_text_frame("TALB", track.album),
            id3_text_frame("TYER", track.year),
            id3_text_frame("TRCK", track.track_number),
            id3_url_frame("WOAS", track.source_url),
            id3_apic_frame(fetch_artwork(track.artwork_url)),
        ]
    )
    if not frames:
        return

    tag = b"ID3\x03\x00\x00" + synchsafe_size(len(frames)) + frames
    data = strip_existing_id3v2(path.read_bytes())
    path.write_bytes(tag + data)
    print("[metadata] tagged mp3")


def normalized_words(value: str) -> set[str]:
    return {word for word in WORD_CHARS.sub(" ", value.casefold()).split() if word}


def normalized_text(value: str) -> str:
    return " ".join(WORD_CHARS.sub(" ", value.casefold()).split())


def normalized_compact_text(value: str) -> str:
    return WORD_CHARS.sub("", value.casefold())


def primary_artist_words(artists: str) -> set[str]:
    primary = re.split(r";|,|&|\bfeat\.?\b|\bft\.?\b", artists, flags=re.I)[0]
    return normalized_words(primary)


def candidate_duration_ms(candidate: dict) -> int | None:
    duration = candidate.get("duration")
    if isinstance(duration, (int, float)):
        return int(duration * 1000)
    duration_string = candidate.get("duration_string")
    if not isinstance(duration_string, str) or ":" not in duration_string:
        return None

    total = 0
    for part in duration_string.split(":"):
        if not part.isdigit():
            return None
        total = total * 60 + int(part)
    return total * 1000


def youtube_candidate_url(candidate: dict) -> str | None:
    for key in ("webpage_url", "original_url", "url"):
        value = candidate.get(key)
        if isinstance(value, str) and value.startswith(("http://", "https://")):
            return value
    video_id = candidate.get("id")
    if video_id:
        return f"https://www.youtube.com/watch?v={video_id}"
    return None


def youtube_match_details(track: TrackMetadata, candidate: dict) -> dict[str, object]:
    title = str(candidate.get("title") or "")
    channel = str(candidate.get("channel") or candidate.get("uploader") or "")
    haystack_words = normalized_words(f"{title} {channel}")
    track_words = normalized_words(track.track)
    artist_words = primary_artist_words(track.artists)
    album_words = normalized_words(track.album)
    track_compact = normalized_compact_text(track.track)
    title_compact = normalized_compact_text(title)
    expected_duration = track.duration_ms
    actual_duration = candidate_duration_ms(candidate)
    duration_delta = abs(expected_duration - actual_duration) if expected_duration and actual_duration else None
    title_exact = bool(track_words and track_words.issubset(haystack_words))
    title_compact_exact = bool(track_compact and track_compact in title_compact)

    return {
        "title_words": track_words,
        "artist_words": artist_words,
        "album_words": album_words,
        "haystack_words": haystack_words,
        "title_exact": title_exact or title_compact_exact,
        "title_word_exact": title_exact,
        "title_compact_exact": title_compact_exact,
        "artist_exact": bool(artist_words and artist_words.issubset(haystack_words)),
        "title_overlap": len(track_words.intersection(haystack_words)),
        "artist_overlap": len(artist_words.intersection(haystack_words)),
        "duration_delta": duration_delta,
    }


def score_youtube_candidate(track: TrackMetadata, candidate: dict) -> tuple[int, list[str]]:
    title = str(candidate.get("title") or "")
    channel = str(candidate.get("channel") or candidate.get("uploader") or "")
    haystack = normalized_text(f"{title} {channel}")
    details = youtube_match_details(track, candidate)
    haystack_words = details["haystack_words"]
    track_words = details["title_words"]
    artist_words = details["artist_words"]
    album_words = details["album_words"]

    score = 0
    reasons: list[str] = []

    if details["title_exact"]:
        score += 45
        reasons.append("title" if details["title_word_exact"] else "title-compact")
    else:
        overlap = int(details["title_overlap"])
        if overlap:
            score += min(25, overlap * 8)
            reasons.append("partial-title")

    if details["artist_exact"]:
        score += 35
        reasons.append("artist")
    else:
        overlap = int(details["artist_overlap"])
        if overlap:
            score += min(20, overlap * 8)
            reasons.append("partial-artist")

    if album_words and album_words.intersection(haystack_words):
        score += 8
        reasons.append("album")

    if any(phrase in haystack for phrase in GOOD_MATCH_PHRASES):
        score += 12
        reasons.append("official-ish")

    delta = details["duration_delta"]
    if isinstance(delta, int):
        if delta <= 3000:
            score += 35
            reasons.append("duration-exact")
        elif delta <= 10000:
            score += 22
            reasons.append("duration-close")
        elif delta <= 30000:
            score += 8
            reasons.append("duration-near")
        else:
            score -= 25
            reasons.append("duration-far")

    real_track_words = track_words
    for bad_word in BAD_MATCH_WORDS:
        if bad_word in haystack_words and bad_word not in real_track_words:
            score -= 16
            reasons.append(f"penalty-{bad_word}")

    view_count = candidate.get("view_count")
    if isinstance(view_count, int):
        if view_count >= 1_000_000:
            score += 5
        elif view_count < 1_000:
            score -= 3

    return score, reasons


def youtube_match_rank(track: TrackMetadata, candidate: dict, score: int) -> tuple[int, int, int, int]:
    details = youtube_match_details(track, candidate)
    title_exact = bool(details["title_exact"])
    artist_exact = bool(details["artist_exact"])
    title_overlap = int(details["title_overlap"])
    artist_overlap = int(details["artist_overlap"])
    duration_delta = details["duration_delta"]

    if title_exact and artist_exact and isinstance(duration_delta, int) and duration_delta <= 5000:
        return (5, -duration_delta, score, 0)

    if isinstance(duration_delta, int) and duration_delta <= 10000 and title_exact and (
        artist_exact or artist_overlap > 0
    ):
        return (4, -duration_delta, score, artist_overlap)

    if isinstance(duration_delta, int) and duration_delta <= 10000 and title_overlap > 0 and artist_overlap > 0:
        return (3, -duration_delta, score, title_overlap + artist_overlap)

    if title_exact and artist_exact:
        duration_penalty = -duration_delta if isinstance(duration_delta, int) else -999999
        return (2, duration_penalty, score, 0)

    return (1, score, -(duration_delta or 999999), title_overlap + artist_overlap)


def read_youtube_search_candidates(
    track: TrackMetadata,
    cookie_args: list[str],
    search_results: int,
) -> list[dict]:
    query_text = f"{track.artists} - {track.track} {track.album}".translate(PUNCTUATION_TRANSLATION)
    query = f"ytsearch{search_results}:{query_text}"
    cmd = [
        "yt-dlp",
        "--flat-playlist",
        "--dump-single-json",
        "--skip-download",
        "--ignore-errors",
        "--no-warnings",
        *cookie_args,
        query,
    ]
    completed = subprocess.run(cmd, check=False, capture_output=True, text=True)
    if not completed.stdout.strip():
        message = completed.stderr.strip() or f"yt-dlp exited with status {completed.returncode}"
        raise RuntimeError(f"Could not search YouTube for {track.artists} - {track.track}: {message}")

    try:
        data = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        message = completed.stderr.strip() or f"yt-dlp exited with status {completed.returncode}"
        raise RuntimeError(f"Could not parse YouTube search results for {track.artists} - {track.track}: {message}") from exc

    return [entry for entry in data.get("entries") or [] if isinstance(entry, dict)]


def resolve_download_url(
    track: TrackMetadata,
    cookie_args: list[str],
    search_results: int,
    min_score: int,
) -> str:
    if track.source_url:
        return track.source_url

    candidates = read_youtube_search_candidates(track, cookie_args, search_results)
    rejected_for_duration = []
    scored = []
    for candidate in candidates:
        if not youtube_candidate_url(candidate):
            continue
        details = youtube_match_details(track, candidate)
        duration_delta = details["duration_delta"]
        if track.duration_ms and isinstance(duration_delta, int) and duration_delta > 10000:
            rejected_for_duration.append((duration_delta, candidate))
            continue
        scored.append((score_youtube_candidate(track, candidate), candidate))

    if not scored:
        if rejected_for_duration:
            best_rejected = min(rejected_for_duration, key=lambda item: item[0])
            title = best_rejected[1].get("title") or youtube_candidate_url(best_rejected[1])
            delta_seconds = best_rejected[0] / 1000
            raise RuntimeError(
                f"No YouTube matches within 10 seconds of ListenBrainz duration. "
                f"Closest was {delta_seconds:.1f}s off: {title}"
            )
        raise RuntimeError(f"No usable YouTube search results for: {track.artists} - {track.track}")

    scored.sort(
        key=lambda item: youtube_match_rank(track, item[1], item[0][0]),
        reverse=True,
    )
    (score, reasons), best = scored[0]
    url = youtube_candidate_url(best)
    title = best.get("title") or url
    if score < min_score:
        raise RuntimeError(
            f"Best YouTube match scored {score}, below --youtube-min-score {min_score}: {title}"
        )

    print(f"[match] {score} ({', '.join(reasons)}) {title}")
    return str(url)


def download_track(
    track: TrackMetadata,
    output_dir: Path,
    dry_run: bool,
    cookie_args: list[str],
    search_results: int,
    min_score: int,
) -> TrackResult:
    if dry_run:
        download_url = track.source_url or f"ytsearch{search_results}:{track.artists} - {track.track} {track.album}"
        print(f"[dry-run] {download_url} -> {track.destination}")
        return TrackResult("dry-run", track.artists, track.track, track.destination, playlist_title=track.playlist_title)

    destination_dir = track.destination.parent

    if track.destination.exists():
        print(f"[skip] {track.destination}")
        write_mp3_metadata(track.destination, track)
        return TrackResult("skipped", track.artists, track.track, track.destination, playlist_title=track.playlist_title)

    destination_dir.mkdir(parents=True, exist_ok=True)

    download_url = resolve_download_url(track, cookie_args, search_results, min_score)

    with tempfile.TemporaryDirectory(prefix="spotify-yt-", dir=output_dir) as tmp:
        temp_dir = Path(tmp)
        cmd = [
            "yt-dlp",
            "--quiet",
            "--no-warnings",
            *cookie_args,
            "-x",
            "--audio-format",
            "mp3",
            "--audio-quality",
            "0",
            "-o",
            str(temp_dir / "%(title).200B [%(id)s].%(ext)s"),
            download_url,
        ]

        print(f"[download] {track.artists} - {track.track}")
        subprocess.run(cmd, check=True)

        mp3s = sorted(temp_dir.glob("*.mp3"), key=lambda item: item.stat().st_mtime, reverse=True)
        if not mp3s:
            raise RuntimeError(f"yt-dlp did not produce an mp3 for: {track.artists} - {track.track}")

        write_mp3_metadata(mp3s[0], track)
        shutil.move(str(mp3s[0]), track.destination)
        print(f"[saved] {track.destination}")
        return TrackResult("downloaded", track.artists, track.track, track.destination, playlist_title=track.playlist_title)


def print_summary(results: list[TrackResult]) -> None:
    downloaded = [result for result in results if result.status == "downloaded"]
    skipped = [result for result in results if result.status == "skipped"]
    dry_runs = [result for result in results if result.status == "dry-run"]
    failed = [result for result in results if result.status == "failed"]

    print("\nSummary")
    print(f"  Downloaded: {len(downloaded)}")
    print(f"  Skipped:    {len(skipped)}")
    print(f"  Dry runs:   {len(dry_runs)}")
    print(f"  Failed:     {len(failed)}")

    def print_result_group(title: str, group: list[TrackResult], include_error: bool = False) -> None:
        if not group:
            return

        print(f"\n{title}")
        for result in group:
            if result.destination:
                print(f"  - {result.label} -> {result.destination}")
            else:
                print(f"  - {result.label}")

            if include_error and result.error:
                print(f"    error: {result.error}")

    print_result_group("Downloaded", downloaded)
    print_result_group("Skipped", skipped)
    print_result_group("Dry Run", dry_runs)
    print_result_group("Failed", failed, include_error=True)


def load_plex_credentials(args: argparse.Namespace) -> tuple[str | None, str | None]:
    plex_url = args.plex_url or os.environ.get("PLEX_URL")
    plex_token = args.plex_token or os.environ.get("PLEX_TOKEN")
    if plex_url:
        plex_url = plex_url.rstrip("/")
    return plex_url, plex_token


def plex_request_xml(
    plex_url: str,
    plex_token: str,
    path: str,
    method: str = "GET",
    headers: dict[str, str] | None = None,
) -> ET.Element:
    url = f"{plex_url}{path}"
    request_headers = {"X-Plex-Token": plex_token}
    request_headers.update(headers or {})
    request = Request(url, method=method, headers=request_headers)
    try:
        with urlopen(request) as response:
            body = response.read()
    except HTTPError as exc:
        details = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Plex API error {exc.code} for {path}: {details}") from exc
    except URLError as exc:
        raise RuntimeError(f"Plex API request failed for {path}: {exc.reason}") from exc

    if not body.strip():
        return ET.Element("MediaContainer")
    return ET.fromstring(body)


def plex_path_for_local_path(path: Path, path_maps: list[str]) -> str:
    value = str(path)
    for item in path_maps:
        if "=" not in item:
            raise RuntimeError(f"Invalid Plex path map '{item}'. Use LOCAL=PLEX.")
        local_prefix, plex_prefix = item.split("=", 1)
        local_prefix = str(Path(local_prefix).expanduser().resolve())
        if value == local_prefix:
            return plex_prefix.rstrip("/")
        if value.startswith(local_prefix.rstrip("/") + "/"):
            suffix = value[len(local_prefix.rstrip("/")) :].lstrip("/")
            return f"{plex_prefix.rstrip('/')}/{suffix}"
    return value


def plex_track_elements(root: ET.Element) -> list[ET.Element]:
    return [element for element in root.iter() if element.tag == "Track"]


def plex_track_file(track: ET.Element) -> str | None:
    for part in track.iter("Part"):
        file_path = part.get("file")
        if file_path:
            return file_path
    return None


def plex_normalized_path(path: str) -> str:
    path = unicodedata.normalize("NFC", path)
    path = path.replace("\\", "/")
    path = SPACE_RUN.sub(" ", path)
    return path.rstrip("/").casefold()


def plex_library_file_map(
    plex_url: str,
    plex_token: str,
    section_id: str,
) -> dict[str, str]:
    rating_keys: dict[str, str] = {}
    start = 0
    size = 1000

    while True:
        root = plex_request_xml(
            plex_url,
            plex_token,
            f"/library/sections/{quote(str(section_id))}/all?type=10",
            headers={
                "X-Plex-Container-Start": str(start),
                "X-Plex-Container-Size": str(size),
            },
        )
        tracks = plex_track_elements(root)
        for track in tracks:
            rating_key = track.get("ratingKey")
            file_path = plex_track_file(track)
            if rating_key and file_path:
                rating_keys[plex_normalized_path(file_path)] = rating_key

        total_size = numeric_value(root.get("totalSize"))
        start += len(tracks)
        if not tracks or total_size is None or start >= total_size:
            break

    return rating_keys


def plex_find_track_rating_key(
    plex_url: str,
    plex_token: str,
    result: TrackResult,
    path_maps: list[str],
    file_rating_keys: dict[str, str] | None = None,
) -> str | None:
    if not result.destination:
        return None

    expected_file = plex_path_for_local_path(result.destination, path_maps)
    expected_key = plex_normalized_path(expected_file)
    if file_rating_keys and expected_key in file_rating_keys:
        return file_rating_keys[expected_key]

    search_params = urlencode({"query": result.track, "type": 10})
    root = plex_request_xml(plex_url, plex_token, f"/search?{search_params}")
    candidates = plex_track_elements(root)

    for candidate in candidates:
        candidate_file = plex_track_file(candidate)
        if candidate_file and plex_normalized_path(candidate_file) == expected_key:
            return candidate.get("ratingKey")

    normalized_track = result.track.casefold()
    normalized_artist = primary_artist_name(result.artists).casefold()
    for candidate in candidates:
        title = (candidate.get("title") or "").casefold()
        artist = (candidate.get("grandparentTitle") or "").casefold()
        if title == normalized_track and artist == normalized_artist:
            return candidate.get("ratingKey")

    return None


def plex_existing_audio_playlist(
    plex_url: str,
    plex_token: str,
    title: str,
) -> ET.Element | None:
    root = plex_request_xml(plex_url, plex_token, "/playlists")
    for playlist in root.iter("Playlist"):
        if playlist.get("playlistType") == "audio" and playlist.get("title") == title:
            return playlist
    return None


def plex_create_audio_playlist(
    plex_url: str,
    plex_token: str,
    machine_id: str,
    title: str,
    rating_keys: list[str],
) -> None:
    uri = f"server://{machine_id}/com.plexapp.plugins.library/library/metadata/{','.join(rating_keys)}"
    params = urlencode({"type": "audio", "title": title, "smart": "0", "uri": uri})
    plex_request_xml(plex_url, plex_token, f"/playlists?{params}", method="POST")


def plex_delete_playlist(plex_url: str, plex_token: str, rating_key: str) -> None:
    plex_request_xml(plex_url, plex_token, f"/playlists/{quote(rating_key)}", method="DELETE")


def plex_lock_track_title(
    plex_url: str,
    plex_token: str,
    section_id: str,
    rating_key: str,
    title: str,
) -> None:
    params = urlencode(
        {
            "type": 10,
            "id": rating_key,
            "title.value": title,
            "title.locked": 1,
        }
    )
    plex_request_xml(plex_url, plex_token, f"/library/sections/{quote(str(section_id))}/all?{params}", method="PUT")


def sync_plex_playlists(results: list[TrackResult], args: argparse.Namespace) -> bool:
    plex_url, plex_token = load_plex_credentials(args)
    if not plex_url and not plex_token:
        return True
    if not plex_url or not plex_token:
        print("Plex sync needs both --plex-url and --plex-token, or PLEX_URL and PLEX_TOKEN.", file=sys.stderr)
        return False
    if args.dry_run:
        print("[plex] Skipping Plex sync during dry run")
        return True

    usable = [
        result
        for result in results
        if result.status in {"downloaded", "skipped"} and result.destination and result.playlist_title
    ]
    if not usable:
        print("[plex] No playlist-backed downloaded/skipped tracks to sync")
        return True

    try:
        root = plex_request_xml(plex_url, plex_token, "/")
        machine_id = root.get("machineIdentifier")
        if not machine_id:
            raise RuntimeError("Could not read Plex machineIdentifier from server root.")

        if args.plex_section_id:
            print(f"[plex] Refreshing library section {args.plex_section_id}")
            plex_request_xml(
                plex_url,
                plex_token,
                f"/library/sections/{quote(str(args.plex_section_id))}/refresh",
            )
            if args.plex_scan_wait > 0:
                time.sleep(args.plex_scan_wait)

        file_rating_keys: dict[str, str] = {}
        if args.plex_section_id:
            print(f"[plex] Reading library file map for section {args.plex_section_id}")
            file_rating_keys = plex_library_file_map(plex_url, plex_token, args.plex_section_id)
            print(f"[plex] Loaded {len(file_rating_keys)} Plex file path(s)")

        grouped: dict[str, list[TrackResult]] = {}
        for result in usable:
            grouped.setdefault(result.playlist_title or "ListenBrainz", []).append(result)

        for playlist_title, playlist_results in grouped.items():
            rating_keys: list[str] = []
            unmatched = playlist_results
            for attempt in range(1, args.plex_match_retries + 1):
                next_unmatched: list[TrackResult] = []
                for result in unmatched:
                    rating_key = plex_find_track_rating_key(
                        plex_url,
                        plex_token,
                        result,
                        args.plex_path_map,
                        file_rating_keys,
                    )
                    if rating_key:
                        rating_keys.append(rating_key)
                        if args.plex_section_id and not args.no_plex_lock_track_titles:
                            plex_lock_track_title(
                                plex_url,
                                plex_token,
                                args.plex_section_id,
                                rating_key,
                                result.track,
                            )
                    else:
                        next_unmatched.append(result)

                unmatched = next_unmatched
                if not unmatched or attempt >= args.plex_match_retries:
                    break

                print(
                    f"[plex] Waiting for Plex to index {len(unmatched)} unmatched track(s) "
                    f"before retry {attempt + 1}/{args.plex_match_retries}"
                )
                time.sleep(args.plex_match_wait)
                if args.plex_section_id:
                    file_rating_keys = plex_library_file_map(plex_url, plex_token, args.plex_section_id)

            for result in unmatched:
                print(f"[plex] Could not match in Plex: {result.label}")

            if not rating_keys:
                print(f"[plex] No Plex tracks found for playlist: {playlist_title}")
                continue

            existing = plex_existing_audio_playlist(plex_url, plex_token, playlist_title)
            if existing is not None:
                if not args.plex_replace_playlists:
                    print(f"[plex] Playlist already exists, leaving it alone: {playlist_title}")
                    continue
                rating_key = existing.get("ratingKey")
                if rating_key:
                    plex_delete_playlist(plex_url, plex_token, rating_key)

            plex_create_audio_playlist(plex_url, plex_token, machine_id, playlist_title, rating_keys)
            print(f"[plex] Created playlist '{playlist_title}' with {len(rating_keys)} track(s)")
    except (RuntimeError, ET.ParseError) as exc:
        print(f"[plex] {exc}", file=sys.stderr)
        return False

    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download Spotify, YouTube Music, CSV, and ListenBrainz playlists from YouTube.",
        epilog=(
            "Examples:\n"
            "  ./downloader.py playlist1.csv playlist2.csv\n"
            "  ./downloader.py 'https://open.spotify.com/track/...' "
            "'https://open.spotify.com/album/...'\n"
            "  ./downloader.py playlist.csv 'https://open.spotify.com/playlist/...'\n"
            "  ./downloader.py 'https://music.youtube.com/playlist?list=...'\n"
            "  ./downloader.py listenbrainz:joebrothehobo"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "sources",
        nargs="+",
        help="CSV path(s), Spotify URL(s), YouTube Music URL(s), or ListenBrainz source(s).",
    )
    parser.add_argument("-o", "--output-dir", default=Path("Music"), type=Path)
    parser.add_argument("--limit", type=int, help="Download only the first N tracks.")
    parser.add_argument("--dry-run", action="store_true", help="Show searches and output paths without downloading.")
    parser.add_argument(
        "--youtube-search-results",
        type=int,
        default=10,
        help="Number of YouTube search results to score for metadata-only tracks. Default: 10.",
    )
    parser.add_argument(
        "--youtube-min-score",
        type=int,
        default=50,
        help="Minimum score required before downloading a YouTube search match. Default: 50.",
    )
    parser.add_argument(
        "--cookies-from-browser",
        metavar="BROWSER",
        help="Use browser cookies for YouTube, for example: chrome, safari, firefox, edge, brave.",
    )
    parser.add_argument(
        "--cookies",
        type=Path,
        help="Use a cookies.txt file for YouTube authentication.",
    )
    parser.add_argument(
        "--spotify-client-id",
        help="Spotify API client ID. Defaults to SPOTIFY_CLIENT_ID.",
    )
    parser.add_argument(
        "--spotify-client-secret",
        help="Spotify API client secret. Defaults to SPOTIFY_CLIENT_SECRET.",
    )
    parser.add_argument("--plex-url", help="Plex server URL. Defaults to PLEX_URL.")
    parser.add_argument("--plex-token", help="Plex token. Defaults to PLEX_TOKEN.")
    parser.add_argument(
        "--plex-section-id",
        help="Optional Plex music library section ID to refresh before playlist creation.",
    )
    parser.add_argument(
        "--plex-scan-wait",
        type=int,
        default=20,
        help="Seconds to wait after a Plex library refresh before searching for tracks. Default: 20.",
    )
    parser.add_argument(
        "--plex-match-retries",
        type=int,
        default=3,
        help="Number of Plex matching attempts after refresh. Default: 3.",
    )
    parser.add_argument(
        "--plex-match-wait",
        type=int,
        default=30,
        help="Seconds to wait between Plex matching attempts. Default: 30.",
    )
    parser.add_argument(
        "--plex-path-map",
        action="append",
        default=[],
        metavar="LOCAL=PLEX",
        help="Map local output paths to Plex-visible paths, for example /Users/me/Music=/music.",
    )
    parser.add_argument(
        "--plex-replace-playlists",
        action="store_true",
        help="Delete and recreate matching Plex audio playlists instead of leaving existing playlists untouched.",
    )
    parser.add_argument(
        "--no-plex-lock-track-titles",
        action="store_true",
        help="Do not edit/lock Plex track titles to the downloaded metadata title.",
    )
    return parser.parse_args()


def main() -> int:
    load_env_file(Path(".env"))
    args = parse_args()
    output_dir = args.output_dir.expanduser().resolve()

    if shutil.which("yt-dlp") is None and not args.dry_run:
        print("yt-dlp is not installed or is not on PATH.", file=sys.stderr)
        return 1

    if args.cookies_from_browser and args.cookies:
        print("Use either --cookies-from-browser or --cookies, not both.", file=sys.stderr)
        return 1

    cookie_args = build_cookie_args(args)

    try:
        tracks = read_sources(args.sources, output_dir, args, cookie_args)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1

    if args.limit is not None:
        tracks = tracks[: args.limit]

    results: list[TrackResult] = []
    for index, track in enumerate(tracks, start=1):
        try:
            print(f"\n[{index}/{len(tracks)}]")
            results.append(
                download_track(
                    track,
                    output_dir,
                    args.dry_run,
                    cookie_args,
                    args.youtube_search_results,
                    args.youtube_min_score,
                )
            )
        except (RuntimeError, subprocess.CalledProcessError) as exc:
            error = str(exc)
            results.append(
                TrackResult(
                    "failed",
                    track.artists,
                    track.track,
                    track.destination,
                    error=error,
                    playlist_title=track.playlist_title,
                )
            )
            print(f"[error] {error}", file=sys.stderr)

    print_summary(results)

    plex_ok = sync_plex_playlists(results, args)

    if any(result.status == "failed" for result in results):
        return 1
    if not plex_ok:
        return 1

    print("\nDone.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
